exports.elemento = {
  buttonEntrar: ("button", "Entrar"),
  buttonEditarBatidas: 'ul[class="dropdown-menu show"]',
  buttonAdicionarOutrasBatidas: ("button", "Adicionar outras batidas"),
  buttonSalvar: ("button", "Salvar"),
  containerMenu: ".po-menu-body",
  inputLogin: 'input[name="user"]',
  inputSenha: 'input[name="password"]',
  inputHoras: 'input[name="hourInput"]',
  inputJustificativa: 'input[name="justificationInput"]',
  menuPonto: (".po-menu-item-wrapper", "Ponto"),
  painelBatidas: ".mat-expansion-panel",
  subMenuEspelhoPonto: ("a", "Espelho de ponto"),
  tabelaData: "table tbody tr",
};
